const express = require('express');
const homeController = require('../controllers/home_controller');
const router = express.Router();
console.log('Router Loaded');
router.get('/', homeController.home);
router.get('/covid-19', homeController.covid);
router.get('/about-us', homeController.about);
router.get('/counseling/depression', homeController.depression);
router.get('/counseling/relationships', homeController.relationships);
router.get('/counseling/stress-&-anxiety', homeController.stressAndAnxiety);
router.get('/counseling/work-stress', homeController.workStress);
router.get('/services/for-individuals', homeController.individuals);
router.get('/services/for-corporates', homeController.corporates);
router.get('/exercises/do-it-yourself', homeController.DIY);
router.get('/info/blogs', homeController.blogs);
router.get('/info/blogs/mental-health-the-real-game-changer', homeController.blogMental);
router.get('/info/blogs/developing-perceptions-from-conception-to-teenage', homeController.blogMental2);
router.get('/info/blogs/healing-relationships', homeController.blogMental3);
router.get('/counseling/book-asession', homeController.bookASession);
router.post('/book-session', homeController.booking);
module.exports = router;